export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const ADD_ITEM_TO_CART_SUCCESS = "ADD_ITEM_TO_CART_SUCCESS";

export const REMOVE_ITEM_FROM_CART_SUCCESS = "REMOVE_ITEM_FROM_CART_SUCCESS";
export const ADD_ITEM_TO_CART_FAIL = "ADD_ITEM_TO_CART_FAIL";
export const REMOVE_ITEM_FROM_CART_FAIL = "REMOVE_ITEM_FROM_CART_FALI";



export const CART_LIST_REQUEST = "CART_LIST_REQUEST";
export const CART_LIST_SUCCESS = "CART_LIST_SUCCESS";
export const CART_LIST_FAIL = "CART_LIST_FAIL";

export const CLEAR_ALL="CLEAR_ALL";
export const CLEAR_ALL_SUCCESS="CLEAR_ALL_SUCCESS";
export const CLEAR_ALL_FAIL="CLEAR_ALL_FAIL";



